### ISSUE TITLE
build failed on windows

### ISSUE THREAD

**Issue by ktfth** [leocavalcante/rust-snake#2]
(tf) C:\Users\Samsung Odyssey\war\rust-snake>cargo build
    Updating crates.io index
  Downloaded rand v0.7.2
  Downloaded sdl2 v0.32.2
  Downloaded getrandom v0.1.14
  Downloaded rand_chacha v0.2.1
  Downloaded rand_core v0.5.1
  Downloaded lazy_static v1.4.0
  Downloaded num v0.1.42
  Downloaded rand v0.6.5
  Downloaded cfg-if v0.1.10
  Downloaded sdl2-sys v0.32.6
  Downloaded bitflags v1.2.1
  Downloaded num-integer v0.1.41
  Downloaded num-iter v0.1.39
  Downloaded rand_chacha v0.1.1
  Downloaded libc v0.2.66
  Downloaded c2-chacha v0.2.3
  Downloaded rand_jitter v0.1.4
  Downloaded rand_hc v0.1.0
  Downloaded num-traits v0.2.10
  Downloaded autocfg v0.1.7
  Downloaded rand_isaac v0.1.1
  Downloaded rand_os v0.1.3
  Downloaded rand_core v0.4.2
  Downloaded rand_pcg v0.1.2
  Downloaded rand_xorshift v0.1.1
  Downloaded ppv-lite86 v0.2.6
  Downloaded rand_core v0.3.1
  Downloaded winapi v0.3.8
   Compiling autocfg v0.1.7
   Compiling rand_core v0.4.2
   Compiling cfg-if v0.1.10
   Compiling winapi v0.3.8
   Compiling getrandom v0.1.14
   Compiling libc v0.2.66
   Compiling bitflags v1.2.1
   Compiling ppv-lite86 v0.2.6
   Compiling sdl2 v0.32.2
   Compiling lazy_static v1.4.0
   Compiling sdl2-sys v0.32.6
   Compiling rand_core v0.3.1
   Compiling c2-chacha v0.2.3
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_core v0.5.1
   Compiling num-traits v0.2.10
   Compiling num-integer v0.1.41
   Compiling num-iter v0.1.39
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling rand_chacha v0.2.1
   Compiling rand v0.7.2
   Compiling num v0.1.42
   Compiling rand_jitter v0.1.4
   Compiling rand_os v0.1.3
   Compiling rust-snake v0.1.0 (C:\Users\Samsung Odyssey\war\rust-snake)
warning: unused `std::result::Result` that must be used
  --> src\main.rs:75:13
   |
75 |             canvas.fill_rect(Rect::new(self.body[i].x, self.body[i].y, SCALE, SCALE));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: this `Result` may be an `Err` variant, which should be handled

warning: unused `std::result::Result` that must be used
   --> src\main.rs:160:9
    |
160 |         canvas.fill_rect(Rect::new(self.pos.x, self.pos.y, SCALE, SCALE));
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this `Result` may be an `Err` variant, which should be handled

error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x86\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LARGEADDRESSAWARE" "/SAFESEH" "/LIBPATH:C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.15226mn3xrcvdalr.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.1e7orvr1c1uivq0v.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.1fy6hi4ivlyv9bc2.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.1gkzqypburdb6m1d.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.1ldy9f2in6ra11ci.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.1p69bovbz19v26m0.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.1s672m4cns980stp.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.1vfyfq072u7gnufe.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.1xhhijnn6f0v95gb.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.21a64gc4djv4zvsz.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.2ex7gofu25p9300e.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.2fyfvccx5uo14cfj.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.2gdcrnk094s3jsts.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.2ino6nj2kwhctb3y.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.2kjrzanlatbv1ti4.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.2om8talqyqciz6ai.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.2yf55q1ywdooekx1.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.345q2ileal47ajhb.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.3el6400jiynuna62.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.3hzqqsrv50ic9djv.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.3lqnrn74opv1a9ni.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.3nsb7g7gw76hj9ik.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.3pe9ko736aee0jec.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.3uk0oo1uwfsj94te.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.3wlpw28vxopdry6o.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.45b19tzqyv97la8k.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.4bqorfqkpofb1bg2.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.4g0zg3f8jxqz0clt.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.4ku6p49pdz2arsew.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.4sbdp21cczhaffcf.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.4v8finuvpxv7vqd9.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.50kjhim9re880a4.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.50wpxm1re0z0qhwy.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.56zwivaw3onsg1mk.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.5764jg6sugzabb1z.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.57tooeaue6n1qk0s.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.5bqu1c5jes2evqif.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.5fp83ccqzg9eumkz.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.6mru5j8p9n2ho9y.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.7v84mqvydgdlih9.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.ca36zexdbhdsyj7.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.nvzatqbh9k6yahx.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.oe9oybdhxx5xhho.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.oflqflrg27nyfsd.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.q1m1aq2oyoe7ir6.rcgu.o" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.taueb7ddca5pzl5.rcgu.o" "/OUT:C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.exe" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\rust_snake.270y81jhsnk7zp65.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps" "/LIBPATH:C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libsdl2-fc1dfeb00ff2b187.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand-588de318488d6ee5.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_xorshift-94f6309ba84a57a9.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_pcg-e1aabab76cb5cf04.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_hc-ddd6186ade9bb572.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_chacha-246f2ae195d5b46a.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_isaac-d0a8eae44d8b5075.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_core-dd7737a8115af27e.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_os-228a55a028b1a70e.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_jitter-e3c213a7d1bbe060.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libwinapi-53d512606140084a.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_core-f110f22b1109011f.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libsdl2_sys-74be17b2958f53da.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libbitflags-b82b89df635e348f.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\liblazy_static-69dded8110ff5ef1.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\liblibc-3a50c18b935f8961.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libnum-f32c1230185c9c2d.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libnum_iter-07389a053159ea8f.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libnum_integer-38ce30b015c61256.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libnum_traits-03f23f9cc274c75f.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand-26dc0907704345be.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_chacha-39be5d7df0a17e97.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libc2_chacha-f7e06d94666b42ec.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libppv_lite86-6e5378f73d6797f7.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\librand_core-673f1c1790080b66.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libgetrandom-e9e2b20689125dc7.rlib" "C:\\Users\\Samsung Odyssey\\war\\rust-snake\\target\\debug\\deps\\libcfg_if-23c8711877784f61.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libstd-a2af7cbca70405c4.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libpanic_unwind-8f8ad41ed0b34354.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libhashbrown-3442ca764a847dfc.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-726244614f5a8f3a.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libbacktrace-29b7599014a92286.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_demangle-519f7f7caa7ec7f2.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libunwind-feba7334127a8724.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcfg_if-6d75d87de5ddb74c.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liblibc-7dc5efd24952e919.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liballoc-b95120d391119ce4.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_core-0e624f0b43962fb3.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcore-58985b8c03f907a8.rlib" "C:\\Users\\Samsung Odyssey\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcompiler_builtins-27c1b248396c205c.rlib" "advapi32.lib" "credui.lib" "kernel32.lib" "secur32.lib" "SDL2.lib" "advapi32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: Non-UTF-8 output: LINK : fatal error LNK1181: n\xe3o foi poss\xedvel abrir o arquivo de entrada \'SDL2.lib\'\r\n

error: aborting due to previous error

error: could not compile `rust-snake`.

To learn more, run the command again with --verbose.

(tf) C:\Users\Samsung Odyssey\war\rust-snake>

**Comment by leocavalcante** [comment]
You must have libsdl2 in your environment. I was able to install it using [vcpk](https://github.com/microsoft/vcpkg):
https://github.com/Rust-SDL2/rust-sdl2#windows-msvc-with-vcpkg

**Comment by leocavalcante** [comment]
Closing since its not using SDL anymore.
